<#
.SYNOPSIS
    Deterministically generates the 8 ChatGPT Custom GPT Knowledge bundles
    under chatgpt/knowledge/ from an explicit allowlist of canonical
    repository sources.

.DESCRIPTION
    See chatgpt/knowledge-manifest.md for the full bundle-to-source mapping
    and rationale. Never edit a file under chatgpt/knowledge/ directly —
    rebuild it with this script (or build-chatgpt-knowledge.sh).

    Works when invoked from inside or outside the repository root, since all
    paths are resolved relative to this script's own location ($PSScriptRoot).
    Compatible with Windows PowerShell 5.1 and PowerShell 7+.
#>

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Fail {
    param([string]$Message)
    Write-Error "error: $Message"
    exit 1
}

$RepoRoot = Split-Path -Parent $PSScriptRoot
$KnowledgeDir = Join-Path $RepoRoot "chatgpt\knowledge"

$GeneratedNotice = @"
<!--
Generated from canonical Career Targeting Intelligence repository sources.
Do not edit this file manually.
Rebuild it using the ChatGPT Knowledge build script
(scripts/build-chatgpt-knowledge.sh or .ps1).
-->
"@

# Explicit bundle -> source allowlist, in generation order.
$Bundles = [ordered]@{
    "01-product-and-terminology.md"        = @("core/product-definition.md", "core/scope-and-non-goals.md", "core/data-model.md")
    "02-candidate-and-search.md"           = @("schemas/candidate-profile.schema.md", "schemas/search-criteria.schema.md", "workflows/analyze-candidate.md", "workflows/build-search-criteria.md")
    "03-company-intelligence.md"           = @("schemas/company-record.schema.md", "workflows/discover-companies.md", "workflows/classify-and-rank-companies.md", "ranking/company-ranking-model.md")
    "04-people-and-activity.md"            = @("schemas/person-record.schema.md", "schemas/activity-record.schema.md", "workflows/discover-people.md", "workflows/verify-activity.md")
    "05-ranking-and-exclusions.md"         = @("ranking/person-ranking-model.md", "ranking/exclusion-policy.md", "ranking/outreach-priority-model.md")
    "06-workflow-and-state.md"             = @("core/workflow.md", "schemas/research-state.schema.md", "workflows/full-journey.md", "workflows/focused-task-routing.md", "workflows/resume-journey.md", "workflows/build-outreach-queue.md")
    "07-evidence-confidence-freshness.md"  = @("core/source-policy.md", "core/confidence-model.md", "core/freshness-policy.md", "core/quality-gates.md")
    "08-output-contracts.md"               = @("core/output-contracts.md", "outputs/candidate-profile-template.md", "outputs/search-criteria-template.md", "outputs/company-map-template.md", "outputs/excluded-companies-template.md", "outputs/people-map-template.md", "outputs/activity-verification-template.md", "outputs/outreach-queue-template.md", "outputs/csv-column-contracts.md")
}

# Validate every canonical source exists before generating anything.
foreach ($bundleName in $Bundles.Keys) {
    foreach ($src in $Bundles[$bundleName]) {
        $srcPath = Join-Path $RepoRoot $src
        if (-not (Test-Path -LiteralPath $srcPath -PathType Leaf)) {
            Fail "required canonical source not found: $srcPath"
        }
    }
}

if (-not (Test-Path -LiteralPath $KnowledgeDir)) {
    New-Item -ItemType Directory -Path $KnowledgeDir -Force | Out-Null
}

# Remove stale generated files not on the current allowlist.
$AllowedNames = $Bundles.Keys
if (Test-Path -LiteralPath $KnowledgeDir) {
    Get-ChildItem -LiteralPath $KnowledgeDir -Filter "*.md" -File |
        Where-Object { $AllowedNames -notcontains $_.Name } |
        Remove-Item -Force
}

# Generate each bundle deterministically.
foreach ($bundleName in $Bundles.Keys) {
    $sources = $Bundles[$bundleName]
    $outPath = Join-Path $KnowledgeDir $bundleName
    $title = [System.IO.Path]::GetFileNameWithoutExtension($bundleName)

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add($GeneratedNotice)
    $lines.Add("")
    $lines.Add("# $title")
    $lines.Add("")

    for ($i = 0; $i -lt $sources.Count; $i++) {
        $src = $sources[$i]
        $srcPath = Join-Path $RepoRoot $src
        $lines.Add("## Source: ``$src``")
        $lines.Add("")
        # Preserve source content without silent rewriting; normalize CRLF to LF.
        $content = Get-Content -LiteralPath $srcPath -Raw
        $content = $content -replace "`r`n", "`n"
        $content = $content.TrimEnd("`n")
        $lines.Add($content)
        if ($i -lt ($sources.Count - 1)) {
            $lines.Add("")
            $lines.Add("---")
            $lines.Add("")
        } else {
            $lines.Add("")
        }
    }

    $finalContent = ($lines -join "`n") + "`n"
    [System.IO.File]::WriteAllText($outPath, $finalContent, (New-Object System.Text.UTF8Encoding($false)))
}

Write-Host "Generated ChatGPT Knowledge bundles in: $KnowledgeDir"
Write-Host ""
Write-Host "Generated files:"
foreach ($bundleName in $Bundles.Keys) {
    Write-Host "chatgpt/knowledge/$bundleName"
}
